
select STUDENT_ID AS Roll_No,
    NAME AS Student_Name,
    DATE_OF_BIRTH AS DOB,
    GENDER AS Sex,
    CONTACT_NO AS Contact,
    DEP_ID AS Department_ID
FROM STUDENT;
SELECT STUDENT_ID AS Roll_No,
    NAME AS Student_Name,
    DEP_ID AS Department_ID
FROM STUDENT;
SELECT FACULTY_ID AS Faculty_ID,
    NAME AS Faculty_Name,
    DESIGNATION AS Faculty_Designation,
    EMAIL AS Faculty_Email
FROM FACULTY;
SELECT COURSE_ID AS ID,
    COURSE_Name AS Name,
    CREDITS AS Points,
    DEP_ID AS Department_ID,
    FACULTY_ID AS Faculty_ID
FROM COURSE;
SELECT ENROLLMENT_ID AS Enroll_ID,
    SEMESTER AS Sem,
    GRADE AS Marks,
    STUDENT_ID AS Std_ID,
    COURSE_ID AS course_ID
FROM ENROLLMENT;
SELECT *
FROM STUDENT
WHERE DEP_ID = 101;
SELECT * 
FROM STUDENT
WHERE GENDER = 'F';
SELECT * 
FROM FACULTY
WHERE DESIGNATION = 'Assistant Professor';
SELECT * 
FROM FACULTY
WHERE DEP_ID = 102;
SELECT *
FROM COURSE
WHERE CREDITS >= 4;
SELECT *
FROM STUDENT
WHERE DATE_OF_BIRTH > DATE'2003-01-01';
SELECT * 
FROM ENROLLMENT
WHERE SEMESTER = '4th';

SELECT * 
FROM STUDENT
ORDER BY NAME ASC;
SELECT * 
FROM STUDENT 
ORDER BY DATE_OF_BIRTH DESC;
SELECT *
FROM FACULTY
ORDER BY DESIGNATION ASC;
SELECT * 
FROM COURSE 
ORDER BY CREDITS DESC;


SELECT * 
FROM STUDENT
FETCH FIRST 3 ROW ONLY;

SELECT * 
FROM COURSE
FETCH FIRST 5 ROW ONLY;



SELECT 
    Name,
    EXTRACT(YEAR FROM sysdate) - EXTRACT(YEAR FROM Date_of_birth) AS DOB
FROM STUDENT;


SELECT 
    COURSE_NAME,
    CREDITS +1 AS UPDATED_CREDITS
FROM COURSE;


SELECT 
    ENROLLMENT_ID,
    SEMESTER ,
    GRADE AS FINAL_GRADE,
    STUDENT_ID,
    COURSE_ID
FROM ENROLLMENT;


SELECT 
    NAME,
    EXTRACT(YEAR FROM DATE_OF_BIRTH) AS YEAR_OF_BIRTH
FROM STUDENT;


SELECT 
    NAME,
    SUBSTR(EMAIL,INSTR(EMAIL , '@')+1) AS EMAIL_DOMAIN
FROM FACULTY;