CREATE TABLE DEPARTMENT 
(
	DEP_ID int Primary Key,
	DEP_NAME VARCHAR(50),
	OFFICE_LOCATION VARCHAR(100)
);
CREATE TABLE STUDENT(
	STUDENT_ID int Primary Key,
	NAME VARCHAR(50),
	DATE_OF_BIRTH DATE,
	GENDER CHAR(1),
	CONTACT_NO VARCHAR(12),
	DEP_ID int,
	FOREIGN KEY(DEP_ID) REFERENCES DEPARTMENT(DEP_ID)
);
CREATE TABLE FACULTY(
	FACULTY_ID int Primary Key,
	NAME VARCHAR(50),
	DESIGNATION VARCHAR(50),
	EMAIL VARCHAR(50),
	DEP_ID int,
	FOREIGN KEY(DEP_ID) REFERENCES DEPARTMENT(DEP_ID)
);
CREATE TABLE COURSE(
	COURSE_ID int Primary Key,
	COURSE_NAME VARCHAR(30),
	CREDITS int,
	DEP_ID int,
	FACULTY_ID int,
	FOREIGN KEY(DEP_ID) REFERENCES DEPARTMENT(DEP_ID),
 FOREIGN KEY(FACULTY_ID) REFERENCES FACULTY(FACULTY_ID)
);
CREATE TABLE ENROLLMENT(
	ENROLLMENT_ID int Primary Key,
	SEMESTER VARCHAR(10),
	GRADE CHAR(2),
	STUDENT_ID int,
	COURSE_ID int,
	FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
	FOREIGN KEY(COURSE_ID) REFERENCES COURSE(COURSE_ID)
);


